### PR TITLE
Fix #930.

### LINKED ISSUE #930: Support Max 2022
The 3ds Max plugin fails to build against the 3ds Max 2022 SDK.

### PR DESCRIPTION
**Pull request by Hoikas**

### CODE REVIEW

File: Sources/Tools/MaxMain/MaxCompat.h [hunk 1]
```diff
@@ -129,6 +129,39 @@ You can contact Cyan Worlds, Inc. by email legal@cyan.com
...
+public:
+    const MCHAR* NonLocalizedClassName() override { return ClassName(); }
+};
+
+class plClassDesc : public ClassDesc
+{
+public:
+    const MCHAR* NonLocalizedClassName() override { return ClassName(); }
+};
+#endif
```
Comment (zrax) [inline Sources/Tools/MaxMain/MaxCompat.h:163]: I wonder if this same pattern can be extended to some of the other nonsense...  For example, instead of having the MAX_NAME_LOCALIZED* macros above, just implement a base class which forwards the flavor with the `localized` parameter to a pure virtual method matching the old signature (which is of course already overridden everywhere)

Comment (Hoikas) [reply Sources/Tools/MaxMain/MaxCompat.h:163]: I was initially thinking the same thing but disregarded it because it would probably require multiple inheritance... The class hierarchy is significantly more complicated for the ones that use the NAME_LOCALIZED junk. Any preference?

Comment (Hoikas) [reply Sources/Tools/MaxMain/MaxCompat.h:163]: Ok, I experimented with changing these all to proxy methods. Unfortately, I wasn't really able to come up with a workable solution. In some cases, Autodesk left the old method signature behind but sealed it so overloading is now an error... eg with `GetObjectName()` and `GetClassName()`. The sealed variant automatically proxies to the new localized one. In other cases, (eg the Sub/Slot/Mtl Name stuff) the method simply gained the `bool localized` with a default argument. I'm really at a loss as to how to make this less terrible.

**Comment by Hoikas** [comment]
Working on compile errors revealed by max plugin CI.

**Comment by Hoikas** [comment]
CI errors fixed.

File: Sources/Tools/MaxMain/MaxCompat.h [hunk 2]
```diff
@@ -175,4 +185,121 @@ static_assert(std::is_same_v<MCHAR, TCHAR>, "MCHAR and TCHAR must have the same
...
+
+protected:
+    // Sealed in Max 2022
+    virtual void IGetClassName(MSTR& s) const { s = _M("Animatable"); }
+    virtual MSTR ISubAnimName(int i) { return _M("no name"); }
+
+public:
+#if MAX_VERSION_MAJOR < 24
+    void GetClassName(MSTR& s) MAX24_CONST override { IGetClassName(s); }
+    void GetClassName(MSTR& s, bool localized) MAX24_CONST { IGetClassName(s); }
```
Comment (zrax) [inline Sources/Tools/MaxMain/MaxCompat.h:213]: This is already in `#if MAX_VERSION_MAJOR < 24`...
```suggestion
    void GetClassName(MSTR& s) override { IGetClassName(s); }
    void GetClassName(MSTR& s, bool localized) { IGetClassName(s); }
```

File: Sources/Tools/MaxMain/MaxCompat.h [hunk 3]
```diff
@@ -175,4 +185,121 @@ static_assert(std::is_same_v<MCHAR, TCHAR>, "MCHAR and TCHAR must have the same
...
+    MSTR SubAnimName(int i) override { return ISubAnimName(i); }
+    MSTR SubAnimName(int i, bool localized) { return ISubAnimName(i); }
+#else
+    void GetClassName(MSTR& s, bool localized) MAX24_CONST override { return IGetClassName(s); }
```
Comment (zrax) [inline Sources/Tools/MaxMain/MaxCompat.h:217]: This is already in `#else` from `#if MAX_VERSION_MAJOR < 24`
```suggestion
    void GetClassName(MSTR& s, bool localized) const override { return IGetClassName(s); }
```

File: Sources/Tools/MaxMain/MaxCompat.h [hunk 4]
```diff
@@ -175,4 +185,121 @@ static_assert(std::is_same_v<MCHAR, TCHAR>, "MCHAR and TCHAR must have the same
...
+protected:
+    // Sealed in Max 2022
+    virtual const MCHAR* IGetName() { return _M("Custom Attribute"); }
+
+public:
+#if MAX_VERSION_MAJOR < 24
+    MAX10_CONST MCHAR* GetName() override { return const_cast<MAX10_CONST MCHAR*>(IGetName()); }
+    MAX10_CONST MCHAR* GetName(bool localized) { return const_cast<MAX10_CONST MCHAR*>(IGetName()); }
+#else
+    MAX10_CONST MCHAR* GetName(bool localized) override { return const_cast<MAX10_CONST MCHAR*>(IGetName()); }
```
Comment (zrax) [inline Sources/Tools/MaxMain/MaxCompat.h:236]: This is already in `#else` of `#if MAX_VERSION_MAJOR < 24`
```suggestion
    const MCHAR* GetName(bool localized) override { return IGetName(); }
```

File: Sources/Tools/MaxMain/MaxCompat.h [hunk 5]
```diff
@@ -175,4 +185,121 @@ static_assert(std::is_same_v<MCHAR, TCHAR>, "MCHAR and TCHAR must have the same
...
+
+public:
+#if MAX_VERSION_MAJOR < 24
+    MAX14_CONST MCHAR* GetObjectName() override { return const_cast<MAX24_CONST MCHAR*>(IGetObjectName()); }
+    MAX14_CONST MCHAR* GetObjectName(bool localized) { return const_cast<MAX24_CONST MCHAR*>(IGetObjectName()); }
+#else
+    MAX14_CONST MCHAR* GetObjectName(bool localized) MAX24_CONST override
+    {
+        return const_cast<MAX24_CONST MCHAR*>(IGetObjectName());
+    }
```
Comment (zrax) [inline Sources/Tools/MaxMain/MaxCompat.h:291]:
```suggestion
    const MCHAR* GetObjectName(bool localized) const override { return IGetObjectName(); }
```

File: Sources/Tools/MaxMain/MaxCompat.h [hunk 6]
```diff
@@ -175,4 +185,121 @@ static_assert(std::is_same_v<MCHAR, TCHAR>, "MCHAR and TCHAR must have the same
...
+    static_assert(std::is_base_of_v<class Object, T>, "plMaxObject can only be used for Object subclasses");
+
+protected:
+    // Sealed in Max 2022
+    virtual const MCHAR* IGetObjectName() const { return _M(""); }
+
+public:
+#if MAX_VERSION_MAJOR < 24
+    MAX14_CONST MCHAR* GetObjectName() override { return const_cast<MAX24_CONST MCHAR*>(IGetObjectName()); }
+    MAX14_CONST MCHAR* GetObjectName(bool localized) { return const_cast<MAX24_CONST MCHAR*>(IGetObjectName()); }
```
Comment (zrax) [inline Sources/Tools/MaxMain/MaxCompat.h:286]:
```suggestion
    MAX14_CONST MCHAR* GetObjectName() override { return const_cast<MAX14_CONST MCHAR*>(IGetObjectName()); }
    MAX14_CONST MCHAR* GetObjectName(bool localized) { return const_cast<MAX14_CONST MCHAR*>(IGetObjectName()); }
```

**Review by zrax — COMMENTED** [review]
Nice, I like this a lot better than the macro hell we were heading towards before...

File: Sources/Tools/MaxMain/MaxCompat.h (hunk 2 above)
Comment (Hoikas) [reply Sources/Tools/MaxMain/MaxCompat.h:213]: Yeah, I was on the fence about this. I was going for consistency in each branch, but if explicit types make more sense...

**Review by zrax — APPROVED** [review]
