### PR TITLE
Fix footstep sounds being in Chinese.

### LINKED ISSUE #1435: PlasmaMax footstep sounds are garbled unicode
plasmamax-footsteps

### PR DESCRIPTION
**Pull request by Hoikas**
Fixes #1435.

### CODE REVIEW

**Review by dpogue — APPROVED** [review]

File: Sources/Plasma/PubUtilLib/plAvatar/plArmatureEffects.h [hunk 1]
```diff
@@ -109,7 +109,7 @@ class plArmatureEffectsMgr : public hsKeyedObject
         kMaxSurface,
         kFootNoSurface = kMaxSurface,
     };  
-    static const char *SurfaceStrings[];
+    static ST::string SurfaceStrings[];
```
Comment (dgelessus) [inline Sources/Plasma/PubUtilLib/plAvatar/plArmatureEffects.h:112]: Technically, `ST::string` hasn't been forward declared yet in this header.

File: Sources/Tools/MaxComponent/plResponderLink.cpp [hunk 2]
```diff
@@ -1606,10 +1606,10 @@ const TCHAR* plResponderCmdFootSurface::GetInstanceName(IParamBlock2 *pb)
 
 #ifdef UNICODE
     _snwprintf(name, std::size(name), L"Foot Surface (%S)",
-        plArmatureEffectsMgr::SurfaceStrings[pb->GetInt(ParamID(kSurface))]);
+        plArmatureEffectsMgr::SurfaceStrings[pb->GetInt(ParamID(kSurface))].c_str());
 #else
     _snprintf(name, std::size(name), "Foot Surface (%s)",
-        plArmatureEffectsMgr::SurfaceStrings[pb->GetInt(ParamID(kSurface))]);
+        plArmatureEffectsMgr::SurfaceStrings[pb->GetInt(ParamID(kSurface))].c_str());
 #endif
```
Comment (dgelessus) [inline Sources/Tools/MaxComponent/plResponderLink.cpp:1613]: `.c_str()` is iffy here - technically this passes UTF-8 into a format expecting ANSI (in practice it doesn't matter, because the strings are pure ASCII). But this entire block can be simplified to:

```suggestion
    _sntprintf(name, std::size(name), _T("Foot Surface (%s)"),
        ST2T(plArmatureEffectsMgr::GetSurfaceName(pb->GetInt(ParamID(kSurface)))));
```

**Review by dgelessus — CHANGES_REQUESTED** [review]

File: Sources/Tools/MaxComponent/plResponderLink.cpp (hunk 2 above)
Comment (Hoikas) [reply Sources/Tools/MaxComponent/plResponderLink.cpp:1613]: This suggestion won't work correctly - it passes a non-trival type (`ST::string`) into printf, and the wrong formatter is used when `UNICODE` is not defined (on Max 2012 and lower). Needs to be `%S` in that situation.

File: Sources/Plasma/PubUtilLib/plAvatar/plArmatureEffects.h (hunk 1 above)
Comment (Hoikas) [reply Sources/Plasma/PubUtilLib/plAvatar/plArmatureEffects.h:112]: True, but I we know it's available due to this being an `hsKeyedObject` subclass.

File: Sources/Tools/MaxComponent/plResponderLink.cpp (hunk 2 above)
Comment (dgelessus) [reply Sources/Tools/MaxComponent/plResponderLink.cpp:1613]: `_sntprintf` maps to the narrow/wide variant depending on whether `UNICODE` is enabled, and `ST2T` does the conversion from `ST::string` to `TCHAR*`, no? (This follows the same pattern as most of the other `GetInstanceName` implementations.)

Comment (Hoikas) [reply Sources/Tools/MaxComponent/plResponderLink.cpp:1613]: It maps to either `_snprintf` (which requires char* to be `%s`) when `UNICODE` is not defined or to `_snwprintf` (which requires char* to be `%S`) when `UNICODE` is defined. Further, non-trival types, such as `ST::string` cannot be passed as arguments to `printf` in general. We had lots of fun fixing those kinds of crashing bugs when we first changed many  C strings to `plString`.

Comment (dgelessus) [reply Sources/Tools/MaxComponent/plResponderLink.cpp:1613]: I don't understand... Unless I'm missing something, it should match up in both cases:

* If `UNICODE` is defined, then `ST2T(s)` becomes `s.to_wchar().data()`, which is a `wchar_t*`, which is appropriate for `%s` in `_snwprintf`
* If `UNICODE` is *not* defined, then `ST2T(s)` becomes `s.to_latin_1().data()`, which is a `char*`, which is appropriate for `%s` in `_snprintf`

It shouldn't make any difference that it was an `ST::string` originally, because it's explicitly converted to a plain C string before it reaches the printf. The C string *is* based on a temporary buffer, but that shouldn't be a problem - IIRC, C++ guarantees that temporary intermediate values stay alive until the end of the statement (i. e. during the entire `_sntprintf` call).

Comment (Hoikas) [reply Sources/Tools/MaxComponent/plResponderLink.cpp:1613]: I think the problem here is that I was forgetting ehat exactly `ST2T` returns. Your suggestion is fine.

File: Sources/Tools/MaxComponent/plResponderLink.cpp [hunk 3]
```diff
@@ -1604,13 +1604,10 @@ const TCHAR* plResponderCmdFootSurface::GetInstanceName(IParamBlock2 *pb)
...
 
-#ifdef UNICODE
-    _snwprintf(name, std::size(name), L"Foot Surface (%S)",
-        plArmatureEffectsMgr::SurfaceStrings[pb->GetInt(ParamID(kSurface))]);
-#else
-    _snprintf(name, std::size(name), "Foot Surface (%s)",
-        plArmatureEffectsMgr::SurfaceStrings[pb->GetInt(ParamID(kSurface))]);
-#endif
+    _sntprintf(
+        name, std::size(name), L"Foot Surface (%s)",
```
Comment (dgelessus) [inline Sources/Tools/MaxComponent/plResponderLink.cpp:1608]:
```suggestion
        name, std::size(name), _T("Foot Surface (%s)"),
```

**Review by dgelessus — APPROVED** [review]

**Review by dpogue — APPROVED** [review]
