### PR TITLE
Fix reported crashes in 3ds Max plugin.

### LINKED ISSUE #934: Max lightmapgen crashes on animation-only files
The workaround is to uncheck the "Generate lightmaps" checkbox on the export panel.

It crashes in `plRenderGlobalContext::MakeRenderInstances` where fInstList is null.

### PR DESCRIPTION
**Pull request by Hoikas**
Fixes #934.

Can't repro #933 yet...

### CODE REVIEW

File: Sources/Tools/MaxConvert/plRenderGlobalContext.cpp [hunk 1]
```diff
@@ -109,7 +109,7 @@ void plRenderGlobalContext::MakeRenderInstances(plMaxNode* root, TimeValue t)
     for (int i = 0; i < root->NumberOfChildren(); i++)
         IMakeRenderInstances((plMaxNode*)root->GetChildNode(i), t, false);
 
-    for (size_t i = 0; i < fInstList.size() - 1; i++)
+    for (hsSsize_t i = 0; i < (hsSsize_t)fInstList.size() - 1; i++)
         fInstList[i].SetNext(&fInstList[i+1]);
```
Comment (zrax) [inline Sources/Tools/MaxConvert/plRenderGlobalContext.cpp:113]: Just a suggestion, instead of making the iteration signed:

```suggestion
    for (size_t i = 1; i < fInstList.size(); i++)
        fInstList[i - 1].SetNext(&fInstList[i]);
```

**Review by zrax — APPROVED** [review]

**Comment by Hoikas** [comment]
Merging per discussion in IRC.
