### PR TITLE
Fix accidental conversion to unsigned in `pfGUIEditBoxMod`

### LINKED ISSUE #1714: Avatar creation name field scrolls oddly if the name is longer than the text field
After typing an avatar name that is longer than the text field, moving the cursor back towards the beginning (using the arrow keys) makes the text start somewhere in the middle of the text field, rather than at the left edge like it's supposed to. Pressing Home makes the text disappear completely until you move the cursor towards the right again.

Haven't tested yet if this also affects other text fields in the game.

Avatar creation dialog with a long name ending in "name be of great length"

The same avatar creation dialog, now showing the start of the name ("long avata"), but the text starts in the middle of the text field instead of at the left edge

### PR DESCRIPTION
**Pull request by dgelessus**
Fixes #1714, supersedes #1717.

### CODE REVIEW

File: Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIEditBoxMod.cpp [hunk 1]
```diff
@@ -132,9 +132,14 @@ void    pfGUIEditBoxMod::IUpdate()
         oldCursorPos = cursorPos;
         cursorPos -= (int16_t)fScrollPos;
 
-        if( 4 + cursorPos > fDynTextMap->GetVisibleWidth() - 4 - 2 )
+        // plDynamicTextMap::GetVisibleWidth returns an unsigned integer.
+        // We have to explicitly convert it to signed,
+        // otherwise the entire comparison will become unsigned and behave incorrectly for negative numbers.
+        ASSERT(fDynTextMap->GetVisibleWidth() <= INT16_MAX);
```
Comment (Hoikas) [inline Sources/Plasma/FeatureLib/pfGameGUIMgr/pfGUIEditBoxMod.cpp]: We should probably use `hsAssert` outside of the networking code.

**Review by Hoikas — APPROVED** [review]
